apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/default-backend: "true"
        io.kompose.service: discovery-server
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_NAME
              value: discovery-server
            - name: 'SPRING_CONFIG_IMPORT '
              value: ' configserver:http://config-server:8071'
            - name: 'SPRING_PROFILES_ACTIVE '
              value: ' default'
          image: anuragbabal/financier-discovery-server:latest
          name: discovery-server
          ports:
            - containerPort: 8070
              hostPort: 8070
              protocol: TCP
          resources:
            limits:
              memory: "268435456"
      restartPolicy: Always
