services:
  network-deploy-service:
    networks:
      - backend

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 256M

  microservice-config-server-config:
    extends:
      service: microservice-base-config
    environment:
      - SPRING_PROFILES_ACTIVE = default
      - SPRING_CONFIG_IMPORT = configserver:http://config-server:8071

  microservice-discovery-server-config:
    extends:
      service: microservice-config-server-config
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE = http://discovery-server:8070/eureka/