services:
  frontend:
    image: "anuragbabal/financier-frontend:latest"
    container_name: financier-frontend
    ports:
      - "80:80"
    extends:
      file: common-config.yaml
      service: network-deploy-service

  config-server:
    image: "anuragbabal/financier-config-server:latest"
    container_name: config-server
    ports:
      - "8071:8080"
    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      - SPRING_APPLICATION_NAME=config-server
    extends:
      file: common-config.yaml
      service: microservice-base-config

  discovery-server:
    image: "anuragbabal/financier-discovery-server:latest"
    container_name: discovery-server
    ports:
      - "8070:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      - SPRING_APPLICATION_NAME=discovery-server
    depends_on:
      config-server:
        condition: service_completed_successfully
    extends:
      file: common-config.yaml
      service: microservice-config-server-config

  expense-service:
    image: "anuragbabal/financier-expense-service:latest"
    container_name: expense-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_APPLICATION_NAME=expense-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://expense-db:3308/expense_db
    depends_on:
      config-server:
        condition: service_completed_successfully
      expense-db:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-config-server-config

  expense-db:
    image: "mysql:8.0"
    container_name: expense-db
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expenses_db
    extends:
      file: common-config.yaml
      service: network-deploy-service

  user-service:
    image: "anuragbabal/financier-user-service:latest"
    container_name: user-service
    ports:
      - "8085:8080"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/user_db
    depends_on:
      config-server:
        condition: service_completed_successfully
      user-db:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-config-server-config

  user-db:
    image: "mysql:8.0"
    container_name: user-db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    extends:
      file: common-config.yaml
      service: network-deploy-service

networks:
  backend:
    driver: bridge