services:
  frontend:
    image: "anuragbabal/financier-frontend:latest"
    container_name: financier-frontend
    ports:
      - "80:80"
    extends:
      file: common-config.yaml
      service: network-deploy-service

  config-server:
    image: "anuragbabal/financier-config-server:latest"
    container_name: config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: "wget -qO- http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    environment:
      - SPRING_APPLICATION_NAME=config-server
    extends:
      file: common-config.yaml
      service: microservice-base-config

  discovery-server:
    image: "anuragbabal/financier-discovery-server:latest"
    container_name: discovery-server
    ports:
      - "8070:8070"
    healthcheck:
      test: "wget -qO- http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    environment:
      - SPRING_APPLICATION_NAME=discovery-server
    depends_on:
      config-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-config-server-config

  gateway-server:
    image: "anuragbabal/financier-gateway-server:latest"
    container_name: gateway-server
    ports:
      - "8072:8072"
    environment:
      - SPRING_APPLICATION_NAME=gateway-server
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-discovery-server-config

  auth-service:
    image: "anuragbabal/financier-auth-service:latest"
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=auth-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://auth-db:3306/financier_auth_db
    depends_on:
      config-server:
        condition: service_healthy
      auth-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-discovery-server-config

  expense-service:
    image: "anuragbabal/financier-expense-service:latest"
    container_name: expense-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_APPLICATION_NAME=expense-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://expense-db:3306/financier_expense_db
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      expense-db:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-discovery-server-config

  user-service:
    image: "anuragbabal/financier-user-service:latest"
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/financier_user_db
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      user-db:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-discovery-server-config

  report-service:
    image: "anuragbabal/financier-report-service:latest"
    container_name: report-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_APPLICATION_NAME=report-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-discovery-server-config

  auth-db:
    image: "mysql:8.0"
    container_name: auth-db
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financier_auth_db
    extends:
      file: common-config.yaml
      service: network-deploy-service

  expense-db:
    image: "mysql:8.0"
    container_name: expense-db
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financier_expense_db
    extends:
      file: common-config.yaml
      service: network-deploy-service

  user-db:
    image: "mysql:8.0"
    container_name: user-db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financier_user_db
    extends:
      file: common-config.yaml
      service: network-deploy-service

networks:
  backend:
    driver: bridge