---
- hosts: localhost
  vars:
    imageName: "anuragbabal/config-server:latest"
    containerName: "config-server"
  tasks:
    - name: Pull the image
      docker_image:
        name: "{{ imageName }}"
        source: pull
        state: present
    - name: Remove the container
      docker_container:
        name: "{{ imageName }}"
        state: absent
    - name: Run the container
      docker_container:
        name: "{{ containerName }}"
        image: "{{ imageName }}"
        state: started
        ports:
          - "8071:8071"
        restart_policy: always