# Server Configuration
server.port=${PORT:8082}

# Spring Application Name
spring.application.name=transaction-service

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/transaction_service_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:financier}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

# JWT Configuration
jwt.secret=${JWT_SECRET:someLongAndSecureSecretKeyThatIsAtLeast256BitsLongForHS256}
jwt.expiration.ms=86400000
