---
- hosts: localhost
  tasks:
    - name: Build image for {{ microservice }}
      docker_image:
        name: "{{ microservice_name }}:latest"
        state: present
        build:
          path: "{{ microservices_dir }}/{{ microservice_name }}"
          dockerfile: Dockerfile

  vars:
    microservices_dir: backend