---
- hosts: localhost
  tasks:
    - name: Delete the old image
      docker_image:
        name: "{{ microservice_name }}:latest"
        state: absent
    - name: Build frontend image
      docker_image:
        name: "{{ microservice_name }}:latest"
        build:
          path: ../frontend
        source: build
        state: present
