---
- hosts: localhost
  become: true
  tasks:
    - name: Build frontend image
      docker_image:
        name: "{{ microservice }}:latest"
        state: present
        build:
          path: frontend
          dockerfile: Dockerfile