---
- hosts: localhost
  tasks:
    - name: Build image for {{ microservice }}
      docker_image:
        name: "{{ microservice }}:latest"
        state: present
        build:
          path: "{{ microservices_dir }}/{{ microservice }}"
          dockerfile: Dockerfile

  vars:
    microservices_dir: backend # Directory where microservices are located