---
- name: Deploy microservices to Kubernetes
  hosts: localhost

  tasks:
    - name: Ensure kubectl is available
      command: which kubectl
      register: kubectl_check
      failed_when: kubectl_check.rc != 0

    - name: Fail if kubectl is not available
      fail:
        msg: "kubectl is not installed or not accessible. Please install and configure kubectl."
      when: kubectl_check.rc != 0

    - name: Create a Namespace from K8S YAML File
      kubernetes.core.k8s:
        src: "create_namespace.yaml"
        state: present

    - name: Apply deployments
      kubernetes.core.k8s:
        src: "{{ deploy_file }}"
        state: present

    - name: Apply services
      kubernetes.core.k8s:
        src: "{{ service_file }}"
        state: present

