---
- hosts: localhost
  tasks:
    - name: Run mvn test for {{ microservice_name }}
      command: mvn test -f {{ microservices_dir }}/{{ microservice_name }}/pom.xml
      register: mvn_test_result

  vars:
    microservices_dir: ../backend