#FROM eclipse-temurin:17-jdk-alpine AS builder
#
#WORKDIR /app
#
#COPY pom.xml ./
#RUN mvn package -DskipTests

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY /target/*.jar app.jar
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
